import Head from 'next/head'
import {Manrope} from '@next/font/google'
import HeaderDescription from "@/components/HeaderDescription";
import BodyDescription from "@/components/BodyDescription";

const inter = Manrope({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="h-[100vh]">
                <HeaderDescription/>
                <BodyDescription/>
            </main>
        </>
    )
}
